DEFAULT = lambda: None

from . import act
from . import asset
from . import auth
from . import br
from . import budget
from . import cap
from . import cms
from . import cr
from . import deploy
from . import disease
from . import doc
from . import dvi
from . import dvr
from . import event
from . import fin
from . import fire
from . import gis
from . import hms
from . import hrm
from . import inv
from . import irs
from . import member
from . import msg
from . import org
from . import patient
from . import pr
from . import proc
from . import project
from . import req
from . import s3
from . import security
from . import sit
from . import stats
from . import supply
from . import sync
from . import translate
from . import transport
from . import vehicle
from . import vol
from . import water
